name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

# sample workflow snippet
steps: 
  - name: Build and deploy
    working-directory: ./app
    run: npm run deploy
    env:
      token: ${{ secrets.MSFT_COMP_VISION_KEY }}
       # deploy token is used to build and deploy to a gh-pages branch 
       # (needs permission to create a branch, build the app and modify that branch, 
       # push changes to that branch, and deploy to github pages)
